apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  ports:
    - name: http
      port: 8080  # Altere para a porta desejada
      targetPort: 8080  # Mantenha o mesmo valor se você não ajustou a porta do argocd-server no Deployment
  selector:
    app.kubernetes.io/name: argocd-server
  type: ClusterIP
