apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: LoadBalancer  # Altera o tipo de serviço para LoadBalancer
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
