apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: default
  annotations:
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: a11c67c5734574c8489c1dfdd8039587-1966979759.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netflix-service
                port:
                  number: 80
