name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Install Docker
        run: |
          sudo apt-get update
          # Remover a versão existente do containerd, se houver
          sudo apt-get remove containerd -y
          # Instalar o containerd.io
          sudo apt-get install -y containerd.io
          # Adicionar o usuário ao grupo docker
          sudo usermod -aG docker $USER
      - name: Verify Docker installation
        run: docker --version
      - name: install trivy
        run: |
          # Install Trivy
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          # Command to scan files
          trivy fs .
      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build --build-arg TMDB_V3_API_KEY=7e8c3da0462a1bef004e78d2cafd71aa -t netflix .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push rodrigosousadf/netflix:latest
        env:
          DOCKER_CLI_ACI: 1
